---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: "Editing hosts entries"
  blockinfile:
    dest: "{{ hosts_file }}"
    block: |
      {{ hosts_entries }}
  when: "hosts_entries is defined and hosts_entries is defined"
